# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shift-schedule-app
spec:
  replicas: 3  # Number of pods to deploy
  selector:
    matchLabels:
      app: shift-schedule
  template:
    metadata:
      labels:
        app: shift-schedule
    spec:
      containers:
      - name: shift-schedule-container
        image: hanstabotabo/mini-proj
        volumeMounts:
        - mountPath: "/data"  # This is the directory inside the container that maps to the PV
          name: shift-schedule-storage
      volumes:
      - name: shift-schedule-storage
        persistentVolumeClaim:
          claimName: shift-schedule-pvc
